### PR TITLE
support background highlights

### PR DESCRIPTION
**Pull request by thenewvu**
I gave an attempt to support background highlights, but you might already know, it's difficult to identify the svg viewbox, without the svg viewbox, the generated svg is not really useful in my opinion. Anyway, nice try, thanks for the work.

### CODE REVIEW

**Comment by phmarek** [comment]
Thanks, I was just looking at the background now... you beat me by a few minutes!

The patch is quite involved - I got a much smaller version, just adding a `<rect width=100% height=100%/>` with a CSS style.

Thanks anyway... sorry for the inconvenience - I was already nearly done when I got the email!

**Comment by thenewvu** [comment]
it's okay, I know my PR is not really useful, I didn't expect the PR to be merged, just want to show the solution, actually the main change is adding the svg `style` attribute with `fill` and `background-color`, the rest is just to try calculate the svg viewport.

**Comment by phmarek** [comment]
No, it was useful! Right on when testing my half-way solution I could compare with your approach, that was helpful!

Although, I couldn't make `<svg>` with `fill` or `background-color` to work in Firefox... that's why I have the `<rect>` in there now.

Do you have a cleaner solution?

**Comment by thenewvu** [comment]
I don't even know svg `fill` attribute and `background-color` css don't work in Firefox, it's hard to support all kinds of SVG viewers, some don't follow the SVG standard. Anyway, I found a post talks about this issue: https://stackoverflow.com/questions/27866893/svg-fill-not-being-applied-in-firefox, looks like it's a well-known issue.

**Pull request closed without merging**
